### ISSUE TITLE
downsampled.tiff is 32bit

### ISSUE THREAD

**Issue by adamltyson** [brainglobe/brainreg-napari#22]
For some reason `downsampled.tiff" is 32 bit, so a) it's huge, and b) doesn't always open properly.

@stephenlenzi Is the saving of this file done by the plugin, or brainreg itself?

**Comment by stephenlenzi** [comment]
that should be handled by brainreg itself

**Comment by adamltyson** [comment]
I've patched this on the brainreg side, but it's not great, we should make sure that the exact same data gets passed to `brainreg.backend.niftyreg.run` in the plugin as the CLI (currently the plugin passes `float64` data).
