### ISSUE TITLE
Check orientation proplem 

### ISSUE THREAD

**Issue by yedeer12** [brainglobe/brainreg-napari#73]
When I check orientation, no matter what data orientation and voxel size I used in the plugin, the first and second input projections look like this. I don't know the reason.

**Computer used (please complete the following information):**
macOS M1 CPU

<img width="1086" alt="image" src="https://github.com/brainglobe/brainglobe-napari-io/assets/104268340/e641fe16-a589-4fda-b01f-e2aea9b82d2c">
<img width="1086" alt="image" src="https://github.com/brainglobe/brainglobe-napari-io/assets/104268340/a2658989-f183-4aef-bdbf-a4e5814ac718">

**Comment by adamltyson** [comment]
Hi @yedeer12, I've transferred this issue because it looks like an issue with the brainreg napari plugin.

Is your data 2D or 3D? brainreg currently only supports 3D data (either a whole brain or hemisphere).

**Comment by yedeer12** [comment]
Oh, my data is 2D. Could brainreg support 2D data in the future?

**Comment by adamltyson** [comment]
We have some work to build a 2D registration tool, but no ETA yet. In the mean time I would recommend [ABBA](https://biop.github.io/ijp-imagetoatlas/registration.html).

**Comment by yedeer12** [comment]
Thanks! If I just have a slice of brain(10um) could I do the registration? How many slices of the brain at least do I need for the registration? Or is it necessary to use the whole brain to do the registration?

**Comment by adamltyson** [comment]
You would need most of the whole brain (i.e. at least 75%). brainreg is a whole-brain 3D registration tool, and just wasn't designed for 2D sections.
